version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
